name: hod_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  dio: ^5.7.0
  excel: ^4.0.6
  file_picker: ^9.2.1
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  mime: ^2.0.0
  path_provider: ^2.1.5
  shared_preferences: ^2.4.0
  syncfusion_flutter_datepicker: ^28.1.41
  syncfusion_flutter_xlsio: ^28.1.41
  url_launcher: ^6.1.14  #Added this dependency

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
